### ISSUE TITLE
Password hashing: Use `password_hash` with Argon2 instead of SHA256

### ISSUE THREAD

**Issue by markusdosch** [kosmat/instant-survey#1]
I would recommend to use the PHP function `password_hash` (with Argon2id as algorithm) instead of `hash`/SHA-256. It is more secure, as it allows you to use recommended password hashing algorithms like Argon2, and makes use of a Salt.

Relevant line: https://github.com/kosmat/instant-survey/blob/9c8867eb09e8ac21da09d44f755427af05cb305e/public/index.php#L163

Relevant docs: 
- General information about password hashing in PHP: https://www.php.net/manual/de/faq.passwords.php
- More information about the function `password_hash`: https://www.php.net/manual/de/function.password-hash.php
- OWASP Password Hashing Cheat Sheet: https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Password_Storage_Cheat_Sheet.md 
- More information on Argon2: https://en.wikipedia.org/wiki/Argon2 & https://cryptobook.nakov.com/mac-and-key-derivation/argon2

**Comment by kosmat** [comment]
Thanks a lot!

I changed the algorithm to Argon2id in 8cd433a.
